### PR TITLE
feat: add notification in place of alert

### PR DESCRIPTION
**Pull request by Wizard254**
This implementation, uses the [Ant Design React UI](https://ant.design/components/notification) framework to show a Notification toast instead of the rather [annoying](https://stackoverflow.com/questions/4920325/is-it-frowned-upon-to-use-js-alerts-with-user) alert dialogue.

### Preview

Screenshot_20240826_212632

### CODE REVIEW

**Comment by xrmaaa** [comment]
Thank you for the pull requests! ❤️ Appreciate your work.

**Comment by reinzsal** [comment]
I’ve changed the repository to a new user, and added vercel.json rewrite so if someone visits root they view the content of /0

**Comment by reinzsal** [comment]
I’ve tried to fix it but I’m unable to since I’m currently on my mobile device, could you set it up so the main page is the root page? Appreciated.

**Comment by Wizard254** [comment]
> I’ve tried to fix it but I’m unable to since I’m currently on my mobile device, could you set it up so the main page is the root page? Appreciated.

If I get you correctly, like the paths https://xr.ma and https://xr.ma/0 should now display the same `fate` contents. I will include that, so that you don't need to include `vercel.json` rewrite.

**Pull request merged**
